# Generated by Django 4.0.2 on 2022-02-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_image_remove_post_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/post/%pk'),
        ),
    ]
